language: minimal

services:
  - docker

script:
  - bash build.sh
  - mkdir deploy
  - cp README.md deploy
  - zip -r deploy/game.zip release/

deploy:
  provider: pages:git
  token: $MY_GITHUB_TOKEN
  edge: true # opt in to dpl v2
  local_dir: deploy