language: minimal

before_install:
  - sudo apt-get -y install dosemu imagemagick xvfb

services:
  - docker

script:
  - bash build.sh
  - bash test.sh
  - zip -r website/game.zip release/
  - xvfb-run bash take_screenshot.sh
  - cp screenshot.png website

deploy:
  provider: pages:git
  token: $MY_GITHUB_TOKEN
  edge: true # opt in to dpl v2
  local_dir: website
  keep_history: false