language: minimal

before_install:
  - sudo apt-get -y install dosemu

services:
  - docker

script:
  - bash build.sh
  - bash test.sh
  - zip -r website/game.zip release/

deploy:
  provider: pages:git
  token: $MY_GITHUB_TOKEN
  edge: true # opt in to dpl v2
  local_dir: website
  keep_history: false